### PR TITLE
[HOLD] Dropdown > Stop keyboard event propagation

### PR DESCRIPTION
**Pull request by Blackbaud-AlexKingman**
This will prevent `Enter`, `ArrowUp`, and `ArrowDown` events from propagation to parent components that may also be listening for keypress events.

### CODE REVIEW

**Comment by Blackbaud-ErikaMcVey** [comment]
The test failures make it look like now navigating with arrows might not be working now?

The way we handled the event propagation for keyboard nav for ag-grid editors was a little different. Instead of stopping the propagation in the skyux component (date time in that case) we added a listener to the datetime component and stopped propagation based on the target. https://github.com/blackbaud/skyux-ag-grid/blob/master/src/app/public/modules/ag-grid/cell-editors/cell-editor-datepicker/cell-editor-datepicker.component.ts#L107-L123

Not sure if that is a better or worse approach, or if there is any use case where another component might need these events propagated.

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-ErikaMcVey oops, I didn't realize it failed, thanks for letting me know. I got a little over-zealous and added an extra `stopPropagation()` that wasn't necessarily hurting anything but still unnecessary. The way that the test was written revealed my mistake. I've removed that and the build should be green now. Thanks!

**Comment by Blackbaud-ErikaMcVey** [comment]
@Blackbaud-AlexKingman I'm thinking about this more and I don't _think_ it will break the ag-grid stuff currently because that is only concerned with tab keypresses, but that is a use case where the parent component does need the event propagated--in some conditions tabbing will navigate the datepicker and the propagation to the parent is stopped, but in others it needs to propagate so the parent component (the cell) can navigate to the next cell. 

I could see consumers relying on the event being propagated for similar reasons, so I don't know if stopping the propagation completely for these keys is the best option. It also seems odd to me that these three keys used for navigation would stop propagation but other keys used for navigation wouldn't--seems like that should be consistent.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-AlexKingman I agree with some of @Blackbaud-ErikaMcVey's points, especially the one about stopping all events or none of the events, for consistency.

Is it possible to add an event listener within the split view component (maybe on a wrapping element of the dropdown) and stop propagation there?

**Comment by Blackbaud-AlexKingman** [comment]
@Blackbaud-SteveBrush Yes - sorry I didn't get in front of you here, but I spoke with Erika and she convinced me to do exactly that. I will probably close this PR if it works out. No action items needed for ya'll here at this point.

**Comment by Blackbaud-AlexKingman** [comment]
Logic has been moved to tree-view component. Closing.

**Pull request closed without merging**
