### PR TITLE
Dropdown docs

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown)

**Comment by Blackbaud-AdamFunderburk** [comment]
Hmm, looks like there are 4 places in Options and Behavior/States that should use `<sky-text-block>`.

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown)

**Comment by Blackbaud-BobbyEarl** [comment]
Preview build at [https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown](https://developer.blackbaud.com/skyux-popovers?_sp.spa=pr-docs-dropdown)

**Pull request merged**
